# Generated by Django 4.2.6 on 2023-12-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_rename_username_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(choices=[('maintain_weight', 'Maintain Weight'), ('gain_weight', 'Gain Weight'), ('lose_weight', 'Lose Weight')], default='maintain_weight', max_length=20),
        ),
    ]
