# Generated by Django 4.2.6 on 2024-01-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_alter_dailycaloriesconsumed_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycaloriesconsumed',
            name='carbs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailycaloriesconsumed',
            name='fat',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailycaloriesconsumed',
            name='food_name',
            field=models.TextField(default='no_name'),
        ),
        migrations.AddField(
            model_name='dailycaloriesconsumed',
            name='protein',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
